#!/bin/sh

#Fix High noise floor when using headphones

amixer -c 0 cset 'numid=10' 1
numid=10,iface=MIXER,name='Headphone Mic Boost Volume'
type=INTEGER,access=rw---R--,values=2,min=0,max=3,step=0
values=1,1
dbscalemin=0.00dB,step=10.00dB,mute=0
