#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
backup_dir=/mnt/Backup

token="1369429125:AAHqxnFKjiHv34-Elh4cFAY98LRGH822jcQ"
chat="668523255"

shutdown="true"

## Start

echo
echo "BORGBACKUP"
echo

if [[ -d "$backup_dir"/data/ ]]; then
    borg list $backup_dir
    echo
else
    echo "No backupdisk found"
    echo "ABORT!"
    exit 0
fi

## Choice

echo "Backup: Daten (0) / Video (1) / Projekt (2) / System (3) / Games (4)"
read -e backup
echo

## Backup Drives

syntax=' '

if [[ $backup == *"0"* ]]; then
    syntax=$syntax' /mnt/Daten/'
fi

if [[ $backup == *"1"* ]]; then
    syntax=$syntax' /mnt/Video/'
fi

if [[ $backup == *"2"* ]]; then
    syntax=$syntax' /mnt/Projekt/'
fi

if [[ $backup == *"3"* ]]; then
    syntax=$syntax' /mnt/Windows/ /home/benny'
fi

if [[ $backup == *"4"* ]]; then
    syntax=$syntax' /mnt/Games/'
fi

## Check

echo FOLLOWING COMMAND WILL BE USED:
echo borg create --progress $backup_dir::$(date +%Y_%m_%d) $syntax
echo

echo "Shutdown after the backup? (y/n)"
read -e shutdown
while [ ! $shutdown == "y" ] && [ ! $shutdown == "n" ]; do
    echo "Invalid answer! Shutdown after the backup? (y/n)"
    read -e shutdown
done

echo
echo Press enter to start backup...
read -e
echo

## Execution + Log

command="borg create --progress --stats $backup_dir::$(date +%Y_%m_%d) $syntax"

echo $command
echo "_____"
startTime=$(date +%s)
$script_dir/telegram -M "*Borg Backup Started*"$'\n'"$command"

$command

endTime=$(date +%s) elapsedTime=$(($endTime - $startTime))

((h = $elapsedTime / 3600))
((m = $elapsedTime % 3600 / 60))
((s = $elapsedTime % 60))

echo $(date +%Y/%m/%d) "("$h:$m:$s")" $command >>$script_dir/backuplog

$script_dir/telegram -M "*Borg Backup Complete* ($h:$m:$s)"$'\n'"$command"

## Shutdown
if [[ shutdown == "y" ]]; then
    echo Shutting down in 60s
    sleep 60
    shutdown
fi
