#!/bin/bash

startTime=$(date +%s)
echo $startTime

sleep 2s

endTime=$(date +%s)
elapsedTime=$(($endTime - $startTime))

((h = $elapsedTime / 3600))
((m = $elapsedTime % 3600 / 60))
((s = $elapsedTime % 60))

testlog="/mnt/Daten/Dokumente/Privat/Dotfiles/testlog"
echo $(date +%Y/%m/%d) "("$h:$m:$s")" >>$testlog
